# Your Discord bot token (Found at https://discord.com/developers/applications)
# æ‚¨çš„ Discord æ©Ÿå™¨äººä»¤ç‰Œï¼ˆåœ¨ https://discord.com/developers/applications æ‰¾åˆ°ï¼‰
botToken: ""

# Your Discord bot client ID
# æ‚¨çš„ Discord æ©Ÿå™¨äººå®¢æˆ¶ç«¯ ID
clientId: ""

# Your Genius API client access token (Found at https://genius.com/developers)
# æ‚¨çš„ Genius API å®¢æˆ¶ç«¯è¨ªå•ä»¤ç‰Œï¼ˆåœ¨ https://genius.com/developers æ‰¾åˆ°ï¼‰
geniusApiKey: ""

# The colour to use for embeds sent by the bot
# æ©Ÿå™¨äººç™¼é€çš„Embedä½¿ç”¨çš„é¡è‰²
embedColour: "#2B2D31"

# Whether the bot should autocomplete search results
# Disable this if you're experiencing Unknown Interaction errors
# æ©Ÿå™¨äººæ˜¯å¦æ‡‰è©²è‡ªå‹•å®Œæˆæœç´¢çµæœ
# å¦‚æœé‡åˆ°æœªçŸ¥çš„äº¤äº’éŒ¯èª¤ï¼Œè«‹ç¦ç”¨æ­¤åŠŸèƒ½
enableAutocomplete: true

# Settings to control the bot's player and controller
# æ§åˆ¶æ©Ÿå™¨äººæ’­æ”¾å™¨å’Œæ§åˆ¶å™¨çš„è¨­ç½®
player:
    # Leave VC when a song ends
    # ç•¶æ­Œæ›²çµæŸæ™‚é›¢é–‹èªéŸ³é »é“
    leaveOnEndDelay: 300000 # 5 minutes
    # Leave VC when a song is stopped
    # ç•¶æ­Œæ›²åœæ­¢æ™‚é›¢é–‹èªéŸ³é »é“
    leaveOnStopDelay: 300000 # 5 minutes
    # Leave VC when the channel is empty
    # ç•¶é »é“ç‚ºç©ºæ™‚é›¢é–‹èªéŸ³é »é“
    leaveOnEmptyDelay: 300000 # 5 minutes
    # Deafen bot while playing
    # æ’­æ”¾æ™‚å°æ©Ÿå™¨äººæ‹’è½
    deafenBot: false

# The emojis to be used in buttons for certain embeds
# See https://github.com/NerdyTechy/Melody/wiki/Using-Custom-Emojis
# ç”¨æ–¼æŸäº›åµŒå…¥å¼æ¶ˆæ¯ä¸­æŒ‰éˆ•çš„è¡¨æƒ…ç¬¦è™Ÿ
# è«‹åƒé–± https://github.com/NerdyTechy/Melody/wiki/Using-Custom-Emojis
emojis:
    stop: "â¹"
    skip: "â­"
    queue: "ğŸ“œ"
    pause: "â¯"
    lyrics: "ğŸ“œ"
    back: "â®"
    autoplay: "Â»"
    shuffle: "ğŸ”€"

# Make Melody use a proxy when making requests.
# Useful if you're experiencing 429 errors.
# See https://github.com/NerdyTechy/Melody/wiki/Proxying-Requests
# Omit user:pass@ if your proxy does not require authentication.
# ä½¿ Melody åœ¨é€²è¡Œè«‹æ±‚æ™‚ä½¿ç”¨ä»£ç†ã€‚
# å¦‚æœæ‚¨é‡åˆ° 429 éŒ¯èª¤ï¼Œé€™å¾ˆæœ‰ç”¨ã€‚
# è«‹åƒé–± https://github.com/NerdyTechy/Melody/wiki/Proxying-Requests
# å¦‚æœæ‚¨çš„ä»£ç†ä¸éœ€è¦èº«ä»½é©—è­‰ï¼Œè«‹çœç•¥ user:pass@
proxy:
    enable: false
    connectionUrl: "http://user:pass@111.111.111.111:8080"

# Make Melody use a custom YouTube cookie when making requests.
# This can help to prevent against receiving 429 rate limits from YouTube.
# See https://github.com/NerdyTechy/Melody/wiki/YouTube-Cookies
# ä½¿ Melody åœ¨é€²è¡Œè«‹æ±‚æ™‚ä½¿ç”¨è‡ªå®šç¾© YouTube cookieã€‚
# é€™å¯ä»¥å¹«åŠ©é˜²æ­¢æ”¶åˆ° YouTube çš„ 429 é€Ÿç‡é™åˆ¶ã€‚
# è«‹åƒé–± https://github.com/NerdyTechy/Melody/wiki/YouTube-Cookies
cookies:
    useCustomCookie: false
    youtubeCookie: ""

# Your YouTube API key (Found at https://console.developers.google.com/)
# æ‚¨çš„ YouTube API é‡‘é‘°ï¼ˆåœ¨ https://console.developers.google.com/ æ‰¾åˆ°ï¼‰
youtubeapikey: ""

# Your Google API key (Found at https://console.developers.google.com/)
# æ‚¨çš„ Google API é‡‘é‘°ï¼ˆåœ¨ https://console.developers.google.com/ æ‰¾åˆ°ï¼‰
googleapikey: ""

# Your OpenAI API key (Found at https://platform.openai.com/)
# æ‚¨çš„ OpenAI API é‡‘é‘°ï¼ˆåœ¨ https://platform.openai.com/ æ‰¾åˆ°ï¼‰
openaiapikey: ""
